[gcp_service_account]
type = "service_account"
project_id = "baseball-pitcher-analyzer"
private_key_id = "52b2d4c7e97a22aedd3f5ff08675f3bcf2f92d6a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcs6ojP/Y6Z86n
N+5BVNbp2CgEuya4IAcaEcu3Oo6PV0VVcernYg5Z/S4Hl0yk9f1yefdHcmvdgwQb
eIoaH5eSmh32wPe0QxIvt/4UB/reyiq8wosxr9qlNhPzKvn4AV00drpVN2Py+hSl
x0+ta0Et8wmfd2LThYzk2BhtqJFb4dAent3PkNwBIfj4Su5ZxrbIRAAJULGia6GS
t6Y7vGidBf4UJg8WkSLfYqZHvbUwwjEuD5jENkdEKmSKnG0RZsK9WlUq7sYgyZRO
lD/npr209O48wgPLv34MHe5/PwOrxQHIyVMbRsdTSW55du7TxO14E6yvgkIiGQRv
pmuTG3CzAgMBAAECggEABta6d/kHJHZk/kbtHCcj4qcUhrGqQhfiZ3YGXNPukSfp
to3BsYvF0jyVQS85C5amvdO/1yY8ZI70DhoydhW8i4veqecIXcgdkj076/Y13HpD
PONaqCD4xa64q9X2JyeGwKQ72T3mcUi5FPZqrkgDhgoDeKpWWE04SxZ5PnPrCsZH
JFLtNAE/N75e+VOXcMVeav5L2pD3l/ir0iUgdnOqTFe6VjSkCBNDg8D9eebiUiQo
E/J3GAJusJkvyxB5G1pevZJBZflcx10akoDts5ZLvyuiHDBGgJTKPm7G2d8kMoW1
IT7ToUb4T6B22H3sS35UpAwZkyd31jAcYrokpeflPQKBgQDLvUkUL+zbNZYAFaYJ
cIXF1jCjoP6kswiBpZ5FWtCbQvlRKB02lL3+7npZaRHquss/OqBoYUsZz09+syle
KZ0fftogV2tHzEEa3stxpGucx2djWEtAwTgV6hEHRVhd5pJeTK2Ze6KEZ5ieY4Ev
ytnnQ5J6N0BpfRuhHNOJzKCLXwKBgQDE5Z4mclr923DgnJmycUYlOqFcHxdlNS14
UGzCA737oBH0hGtXCIiasrNpclKQYnCIiMUgFXMSz5wLhAlaIp/gBgIn4xgUVfIk
HRTaF0EYeQNKnR+gV0DoPWhHErLF5yidhaEsduhlmGVzrO5pNO2yh1H8svgFKM5R
CMFstoOvLQKBgEO4r0nehER5E1sD1yTcGhsgjxpUsU/dkr5FZs522VBCeszXIJ67
4kuSyWhe3G3BmT1zJ06KyIPTvQDIXL/H5UpKyAZoCGjdI+bil402se5y+ZK0Do9/
qjzeiLp5+l17/rsJkcqqpeKM7NX5DT/tlXChrVaidu6Zf02WX1o2gkbRAoGBAMNw
mJbZE/C/jT+msfkp7tKta9WhFvvi2Qt/6TR7umy16pynhFSTp+TGVMfqLoIa9FDS
UbkTEXIumVnk6dOKYt9fl2w4QoKM/RlTtIr2YisEk3vQkr/5W/gqXAOQT9uZI/uX
1O/p56xQpQM5OD09yGNZZsxKaV3Vr1VIN5bNY9DRAoGAfyPnZl0D6H2UBbCK8YRz
l6V3fqcJbPBQJrNMP8aC/KOhIcHaaP2DycqkACoy351oW/DMxqRe5xPzHyvX8Ll5
vsLc2kmf1r9+Kp+ZWX0KvFuNlRJZycruA7ynLDDnoaIdusPg1gib8F/yn/SUuF+B
m7m/EmPNEk6vTfU/1uP0jrg=
-----END PRIVATE KEY-----"""
client_email = "streamlitapp@baseball-pitcher-analyzer.iam.gserviceaccount.com"
client_id = "109985771376139207613"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlitapp%40baseball-pitcher-analyzer.iam.gserviceaccount.com"
universe_domain = "googleapis.com"